#split
n_folds: 3

#Augmentation. Dict keys correspond to the class to augment. 
#0: valid, 1: without ratio, 2: artifact, -1 : all

iterations: {
  -1: {
    n_components: 5,
    n_neighbors: 10,
    var: 10,
    n_gen: 1
  },
  2: {
    n_components: 5,
    n_neighbors: 10,
    var: 50,
    n_gen: 4
  }
}

#quantiles
quantiles: [0.25, 0.75]

#calibration : alpha_0, alpha_1, alpha_2
sets: {
  "1": [0.05, 0.15, 0.05],
  "2": [0.10, 0.20, 0.05]
}


#models
models: {
  XGB: {
    lambda : [0, 1],
  },

  RF: {
    n_estimators: [50, 100]
  },

  MLP: {
    n_layers: [3, 5, 7], 
    hidden_width: [16, 32, 64], 
  }
}

